name: CI

on:
  workflow_call:
  push:
    branches:
      - '**'
    tags:
      - 'v**'

env:
  DENO_VERSION: 2.5.4

jobs:
  deno:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Code Style
        run: deno fmt --check

      - name: Linting
        run: deno lint

      - name: Type Check
        run: deno check scripts/*.ts *.ts

      - name: Tests
        run: |
          deno test --coverage=cov/
          deno coverage cov/

  npm:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - run: deno task build

  size:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - run: deno task gzip

  # https://jsr.io/docs/publishing-packages#publishing-from-github-actions
  # https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry
  publish:
    name: Publish
    needs: [deno, npm]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write # -> authentication
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ env.DENO_VERSION }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: deno task build --quiet

      - name: 'Publish → npm (pre-release)'
        if: ${{ contains(github.ref, '-next.') }}
        run: npm publish --tag next --provenance --access public
        working-directory: ./npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Publish → npm'
        if: ${{ !contains(github.ref, '-next.') }}
        run: npm publish --provenance --access public
        working-directory: ./npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 'Publish → jsr'
        if: ${{ !contains(github.ref, '-next.') }}
        run: deno publish --no-check -c deno.json
